name: Update Release Notes with SHA256 Checksums

on:
  release:
    types: [published]

jobs:
  update-release-notes:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Get release assets
        id: assets
        run: |
          release_tag=${{ github.event.release.tag_name }}
          echo "Fetching assets for release $release_tag"
          assets_url="https://api.github.com/repos/${{ github.repository }}/releases/tags/$release_tag"
          assets=$(curl -s $assets_url | jq -r '.assets[] | .browser_download_url')
          echo "::set-output name=assets::$assets"

      - name: Calculate SHA256 checksums for assets
        id: checksum
        run: |
          assets=(${{
            steps.assets.outputs.assets
          }})
          sha256s=()
          for asset in "${assets[@]}"; do
            echo "Processing asset: $asset"
            asset_filename=$(basename $asset)
            curl -L $asset | sha256sum | awk '{print $1}' > $asset_filename.sha256
            sha256=$(cat $asset_filename.sha256)
            sha256s+=("| $asset_filename | $sha256 |")
          done
          echo "::set-output name=sha256s::${sha256s[@]}"

      - name: Append SHA256 table to release notes
        run: |
          sha256_table="| Filename | SHA256 Checksum |\n| --- | --- |\n${{ steps.checksum.outputs.sha256s }}"
          release_body=$(curl -s -X GET -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/releases/tags/${{ github.event.release.tag_name }} | \
            jq -r '.body')
          updated_body="${release_body}\n\n### SHA256 Checksums\n$sha256_table"
          echo "Updated release notes: $updated_body"

      - name: Update release notes with checksum table
        run: |
          release_id=$(curl -s -X GET -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/releases/tags/${{ github.event.release.tag_name }} | \
            jq -r '.id')
          curl -s -X PATCH -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -d "{\"body\": \"$updated_body\"}" \
            https://api.github.com/repos/${{ github.repository }}/releases/$release_id
