name: Release with SHA256 Checksums

on:
  release:
    types: [published]

jobs:
  update-release-notes:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Get release assets (files) for the current release
      - name: Get release assets
        id: assets
        run: |
          release_tag=${{ github.event.release.tag_name }}
          echo "Fetching assets for release $release_tag"
          assets_url="https://api.github.com/repos/${{ github.repository }}/releases/tags/$release_tag"
          assets=$(curl -s $assets_url | jq -r '.assets[] | .browser_download_url')
          echo "::set-output name=assets::$assets"

      # Step 3: Calculate SHA256 checksums for each asset
      - name: Calculate SHA256 checksums for assets
        id: checksum
        run: |
          assets=(${{
            steps.assets.outputs.assets
          }})
          sha256s=()
          for asset in "${assets[@]}"; do
            echo "Processing asset: $asset"
            asset_filename=$(basename $asset)
            curl -L $asset | sha256sum | awk '{print $1}' > $asset_filename.sha256
            sha256=$(cat $asset_filename.sha256)
            sha256s+=("| $asset_filename | $sha256 |")
          done
          echo "::set-output name=sha256s::${sha256s[@]}"

      # Step 4: Fetch the current release body (to append to it)
      - name: Fetch current release body
        id: get-release-body
        run: |
          release_body=$(curl -s -X GET -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/releases/tags/${{ github.event.release.tag_name }} | \
            jq -r '.body')
          echo "::set-output name=release_body::$release_body"

      # Step 5: Create the SHA256 table in Markdown format
      - name: Create SHA256 table
        id: create-sha256-table
        run: |
          sha256_table="| Filename | SHA256 Checksum |\n| --- | --- |\n${{ steps.checksum.outputs.sha256s }}"
          echo "::set-output name=sha256_table::$sha256_table"

      # Step 6: Append the SHA256 table to the current release notes
      - name: Append SHA256 table to release notes
        run: |
          release_body="${{ steps.get-release-body.outputs.release_body }}"
          sha256_table="${{ steps.create-sha256-table.outputs.sha256_table }}"
          updated_body="$release_body\n\n### SHA256 Checksums\n$sha256_table"
          echo "::set-output name=updated_body::$updated_body"

      # Step 7: Upload release assets using softprops/action-gh-release
      - name: Upload release assets
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ steps.assets.outputs.assets }}
          body: ${{ steps.append-sha256-table.outputs.updated_body }}
          tag_name: ${{ github.event.release.tag_name }}
          token: ${{ secrets.GITHUB_TOKEN }}

